# 自动修复问题
fix = true

# 允许的最大行长度
indent-width = 4
line-length = 88

# 选择兼容的 Python 版本
target-version = "py312"

# 排除检查的目录
exclude = [
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".tox",
    ".venv",
    "build",
    "dist",
]

# 禁用某些规则
ignore = ["E501"] # 忽略行长度超过限制的错误

# 启用的规则集合
select = ["E", "F", "W", "C90", "I"]


[format]
# 启用格式化功能
docstring-code-format = true
indent-style = "space"     # "space" 或 "tab"
# Use `\n` line endings for all files
line-ending = "lf"
quote-style = "double"     # "single" 或 "double"


[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
length-sort = true
lines-after-imports = 2

